### ISSUE TITLE
error Circular view path [login]

### ISSUE THREAD

**Issue by 0d3ng** [hendisantika/spring-boot-security-example#1]
mas @hendisantika ketika saya jalankan kenapa error seperti di bawah ini ya
![Screen Shot 2020-05-30 at 00 42 42](https://user-images.githubusercontent.com/30645300/83288977-7e464e00-a20e-11ea-8705-1220c7fcdbd6.png)

**Comment by hendisantika** [comment]
Wait, saya cek dulu ya

**Comment by hendisantika** [comment]
So far so good sich. Tapi sekalian ane upgrade Spring Boot nya ke 2.3.0.RELEASE version. Jadi banyak perubahan. Mohon di-pull lagi @0d3ng

**Comment by hendisantika** [comment]
Karena gak ada respose selama 4 hari saya close issue nya ya.
