### ISSUE TITLE
UserDetailsService

### ISSUE THREAD

**Issue by klepon46** [hendisantika/spring-boot-security-example#2]
Halo pak hendi,

pak userDetailsService di file SecurityConfig itu bagaimana ya kerjanya, saya agak bingung memahaminya

**Comment by hendisantika** [comment]
Sesuai namanya dia bertugas untuk mengecek semua fitur dari user.

Untuk lebih detailnya bisa dicek link berikut ini:
https://www.boraji.com/spring-security-5-custom-userdetailsservice-example
https://www.logicbig.com/tutorials/spring-framework/spring-security/user-details-service.html
https://www.baeldung.com/spring-security-authentication-with-a-database

**Comment by klepon46** [comment]
> 
> 
> Sesuai namanya dia bertugas untuk mengecek semua fitur dari user.
> 
> Untuk lebih detailnya bisa dicek link berikut ini:
> https://www.boraji.com/spring-security-5-custom-userdetailsservice-example
> https://www.logicbig.com/tutorials/spring-framework/spring-security/user-details-service.html
> https://www.baeldung.com/spring-security-authentication-with-a-database

kenapa ya pak kalau saya coba di project saya, saya harus define lagi UsersDetailsService nya, tapi kalau di contoh bapak langsung bapak lempar aja ke dalam auth.userDetailsService(userDetailsService)

**Comment by hendisantika** [comment]
Harus lihat code nya dulu.
